version: '3'

volumes:
  mysql_data_app:
    driver: local
  redis_data_app:
    driver: local
  mongodb_data_app:
    driver: local

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./apps:/var/www/apps
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 80:80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
  php:
     build: ./php
     volumes:
       - ./apps:/var/www/apps
     working_dir:
       /var/www/apps
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis_data_app:/data
  db:
    #platform: linux/x86_64
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: devapp 
      MYSQL_USER: devuser
      MYSQL_PASSWORD: s3cret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data_app:/var/lib/mysql
    ports:
      - "3306:3306"
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_app:/var/lib/db/
  redis:
   image: redis:latest
   ports:
      - "6379:6379"
